/* Tenotemo Earn pilot. All financial and credit mutations happen in Supabase RPCs. */
(()=>{'use strict';
const $=id=>document.getElementById(id),panel=$('earnPanel');
const text=(tag,value)=>{const el=document.createElement(tag);el.textContent=String(value);return el};
const money=n=>'R'+(Number(n||0)/100).toFixed(2);
const day=(offset=0)=>{const d=new Date(Date.now()+offset*86400000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)};
async function rpc(name,args={}){if(!tUser||!tClient)throw Error('Sign in to use Tenotemo Earn.');const {data,error}=await tClient.rpc(name,args);if(error)throw error;return data}
function note(s){$('earnNotice').textContent=s}
function referral(code){return location.origin+'/api/c?code='+encodeURIComponent(code)}
function directReferral(code){return location.origin+'/api/r?code='+encodeURIComponent(code)}
function shareMessage(c){return `${c.title} — ${c.description||'Approved advertiser promotion'}\n${referral(c.referral_code)}\n#Sponsored #TenotemoEarn`}
async function registerShare(c){const rows=await rpc('tenotemo_register_campaign_share',{p_campaign_id:c.id});const r=Array.isArray(rows)?rows[0]:rows;if(r?.reward_type==='cash')note('Publication registered. This campaign currently qualifies for R1 per approved eligible platform Status/Story. Keep it live for more than 2 hours and reach at least 21 genuine views before admin review.');else note('Paid rewards are used up for this campaign. It is now clearly in Memory Credit mode: an eligible approved Status/Story earns 5 Memory Credits. Keep it live for more than 2 hours and reach at least 21 genuine views.');return r}
async function copyCampaignLink(c){const message=shareMessage(c);try{await navigator.clipboard.writeText(message);note('Campaign message and your unique referral link copied. Paste them alongside your picture or video.')}catch{prompt('Copy your campaign message and referral link:',message)}}
async function share(c){const link=referral(c.referral_code),message=shareMessage(c);
 if(navigator.share){try{await navigator.share({title:c.title,text:message});await registerShare(c);return}catch(e){if(e.name==='AbortError')return;throw e}}
 await copyCampaignLink(c);note('Link copied. Tenotemo can only create the automatic R2 provisional amount after a supported device share completes.');
}
async function shareMedia(c){
 if(!c.referral_code)return note('Unlock this campaign first.');
 const {data:posts,error}=await tClient.from('tenotemo_spotlight_posts').select('image_path,status').eq('id',c.spotlight_post_id).limit(1);
 if(error)throw error;const path=posts?.[0]?.image_path;
 if(!path)return note('This campaign has no approved picture or video. Use Share Campaign Link instead.');
 if(posts[0].status!=='approved')return note('This campaign is not currently available for sharing.');
 const bucket=/\/campaigns\//.test(path)?'tenotemo-campaign-media':'tenotemo-spotlight';
 const {data:signed,error:signError}=await tClient.storage.from(bucket).createSignedUrl(path,300);
 if(signError||!signed?.signedUrl)throw signError||Error('Cannot access approved media.');
 const response=await fetch(signed.signedUrl);if(!response.ok)throw Error('Media download failed.');
 const blob=await response.blob();const ext=path.split('.').pop().toLowerCase();const type=blob.type||({'mov':'video/quicktime','mp4':'video/mp4','webm':'video/webm','jpg':'image/jpeg','jpeg':'image/jpeg','png':'image/png','webp':'image/webp'}[ext]);
 const file=new File([blob],`tenotemo-campaign.${ext}`,{type});
 const message=shareMessage(c);
 if(navigator.share&&navigator.canShare?.({files:[file]})){
  try{await navigator.share({files:[file],text:message,title:c.title});await registerShare(c);return}catch(e){if(e.name==='AbortError')return;throw e}
 }
 const objectURL=URL.createObjectURL(file),a=document.createElement('a');a.href=objectURL;a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(objectURL),60000);
 await copyCampaignLink(c);note('Approved media downloaded. Add it to your post or Status, and paste your copied unique referral link.');
}
async function refresh(){if(!tUser)return note('Sign in to use Tenotemo Earn.');note('Loading your private dashboard…');try{
 const d=await rpc('tenotemo_earn_home');$('earnMemory').textContent=d.memory_credits||0;$('earnProvisional').textContent=money(d.provisional_cents);$('earnApproved').textContent=money(d.approved_cents);$('earnPaid').textContent=money(d.paid_cents);
 let pc=d.points_conversion||{};
 try{const statusRows=await rpc('tenotemo_game_point_credit_status');const live=Array.isArray(statusRows)?statusRows[0]:statusRows;if(live)pc=live}catch(_e){}
 if($('earnPointsStatus'))$('earnPointsStatus').textContent=`Recorded game points: ${Number(pc.total_points||0)} · Already converted: ${Number(pc.converted_points||0)} · Available now: ${Number(pc.available_points??pc.remaining_points??0)} · Claimable credits: ${Number(pc.claimable_credits||0)}`;
 const profile=d.advertiser_profile;const pkg=d.advertiser_package;const ref=d.payment_reference||((tUser&&tUser.id)?'TENOTEMO-'+(d.username||'YOUR-USERNAME'):'');if($('earnPaymentReference'))$('earnPaymentReference').textContent=ref||'Register your advertiser profile first';if($('earnBusinessReference'))$('earnBusinessReference').textContent=ref?'Your EFT reference: '+ref:'';if($('earnCurrentPackage'))$('earnCurrentPackage').innerHTML=pkg&&pkg.package_key?`<strong>${String(pkg.package_key).toUpperCase()} package active</strong><br>Expires ${new Date(pkg.expires_at).toLocaleDateString('en-ZA')} · ${Number(pkg.granted_spotlight_credits||0)} Advertising Credits granted`:'<strong>No active advertiser package yet.</strong><br>Register below, make payment and submit proof for review.';
 if(profile){$('earnAdvertiserType').value=profile.account_type;$('earnAdvertiserName').value=profile.display_name;$('earnAdvertiserService').value=profile.service_description;$('earnAdvertiserArea').value=profile.service_area;$('earnAdvertiserPackage').value=profile.preferred_package;$('earnAdvertiserStatus').textContent='Application saved · Package activation requires payment verification and administrator approval.';}
 const box=$('earnCampaigns');box.replaceChildren();for(const c of d.campaigns||[]){const card=text('article','');card.className='earn-campaign';card.append(text('h3',c.title),text('p',c.description||'Approved advertiser campaign'));
 card.append(text('small',`Unlock: ${c.credit_cost} Memory Credits · One qualifying share per social platform per day · Ends ${new Date(c.ends_at).toLocaleDateString('en-ZA')}`));
 if(c.referral_code){/* Rendering must be read-only. Never call tenotemo_register_campaign_share here: that RPC reserves/registers a share and belongs only to an explicit user share action. */const cashMode=Number(c.awarded_cents||0)<Number(c.reward_budget_cents||0);const rewardBanner=text('p',cashMode?'💵 Share for R1 per approved platform':'🧠 PAID REWARDS USED UP — Share for 5 Memory Credits');rewardBanner.style.cssText='font-weight:800;padding:9px 11px;border:1px solid #cbd5e1;border-radius:10px;margin:8px 0';card.append(rewardBanner,text('p',`Earned cash: ${money(c.approved_cents)} · Share each social platform at most once per day.`));const b=text('button','🔗 Share Campaign Link');b.onclick=()=>share(c);card.append(b);const m=text('button','🖼️ Share Picture / Video');m.style.marginLeft='6px';m.onclick=async()=>{m.disabled=true;try{await shareMedia(c)}catch(e){note('Cannot share media: '+e.message)}finally{m.disabled=false}};card.append(m);const cp=text('button','📋 Copy Referral Link');cp.style.marginLeft='6px';cp.onclick=()=>copyCampaignLink(c);card.append(cp);
 const proof=document.createElement('div');proof.style.cssText='margin-top:10px;padding:10px;border:1px solid #cbd5e1;border-radius:10px';proof.append(text('strong',cashMode?'Submit proof · R1 if approved':'Submit proof · 5 Memory Credits if approved'),text('p','Eligibility check: sponsored Status/Story must be live for more than 2 hours and show at least 21 genuine views. Admin still verifies the proof. Do not expose unnecessary viewer names or phone numbers.'));
 const platform=document.createElement('select');for(const [v,l] of [['whatsapp','WhatsApp Status'],['facebook','Facebook Story'],['instagram','Instagram Story']])platform.add(new Option(l,v));
 const sharedLabel=text('label',' Time shared: ');const shared=document.createElement('input');shared.type='datetime-local';shared.max=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);sharedLabel.append(shared);
 const viewsLabel=text('label',' Views: ');const views=document.createElement('input');views.type='number';views.min='0';views.step='1';views.placeholder='21 or more';views.style.width='110px';viewsLabel.append(views);
 const file=document.createElement('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';
 const submit=text('button','Upload sharing proof');submit.type='button';submit.onclick=async()=>{if(!shared.value)return note('Enter the date and time you shared the campaign.');const viewCount=Number(views.value);if(!Number.isInteger(viewCount)||viewCount<0)return note('Enter the current number of views.');if(!file.files[0])return note('Choose a screenshot showing the campaign, platform and views.');if(file.files[0].size>10*1024*1024)return note('Screenshot must be 10 MB or smaller.');submit.disabled=true;let path='';try{path=`${tUser.id}/share-proofs/${crypto.randomUUID()}.${(file.files[0].name.split('.').pop()||'jpg').toLowerCase()}`;const up=await tClient.storage.from('tenotemo-share-proofs').upload(path,file.files[0],{contentType:file.files[0].type,upsert:false});if(up.error)throw up.error;await rpc('tenotemo_submit_share_proof',{p_campaign_id:c.id,p_platform:platform.value,p_proof_path:path,p_shared_at:new Date(shared.value).toISOString(),p_view_count:viewCount});note(cashMode?'Proof submitted. R1 is pending verification. Approval requires more than 2 hours live and at least 21 verified views.':'Proof submitted. 5 Memory Credits are pending verification. Approval requires more than 2 hours live and at least 21 verified views.');await refresh()}catch(e){if(path)await tClient.storage.from('tenotemo-share-proofs').remove([path]);note('Proof not submitted: '+e.message)}finally{submit.disabled=false}};
 proof.append(document.createElement('br'),platform,document.createElement('br'),sharedLabel,document.createElement('br'),viewsLabel,document.createElement('br'),file,submit);card.append(proof)}
 else{const b=text('button','Unlock campaign');b.onclick=async()=>{b.disabled=true;try{await rpc('tenotemo_earn_join',{p_campaign_id:c.id});note('Campaign unlocked. Share its unique referral link.');await refresh()}catch(e){note(e.message)}finally{b.disabled=false}};card.append(b)}box.append(card)}
 if(!(d.campaigns||[]).length)box.append(text('p','No active campaigns yet. Check back as businesses and service providers join Tenotemo.'));
 note('Your earnings are private. Referral visits are indicative and reviewed before any reward is approved.');loadPayoutHome();
 }catch(e){note('Tenotemo Earn database setup needed: '+e.message)}}
async function loadPayoutHome(){const out=$('earnPayoutStatus');if(!out)return;try{const d=await rpc('tenotemo_player_payout_home');const available=Number(d.available_earned_cents||0),latest=d.latest_request,details=d.details;if(details){$('earnPayoutHolder').value=details.account_holder||'';$('earnPayoutBank').value=details.bank_name||'';const savedType=details.account_type||'Savings';if([...$('earnPayoutType').options].some(o=>o.value===savedType))$('earnPayoutType').value=savedType;$('earnPayoutBranch').value=details.branch_code||'';$('earnPayoutAccount').placeholder=details.account_number_masked?`Saved: ${details.account_number_masked} · enter only to change`:'Account number';const sm=$('earnSavedEftSummary');if(sm)sm.innerHTML=`<small><strong>Saved EFT details:</strong> ${details.account_holder||''} · ${details.bank_name||''} · ${details.account_number_masked||''} · ${savedType}${details.branch_code?' · Branch '+details.branch_code:''}</small>`}else{$('earnPayoutAccount').placeholder='Account number';const sm=$('earnSavedEftSummary');if(sm)sm.innerHTML='<small>No EFT details saved yet.</small>'}if(latest?.status==='pending'){out.textContent=`Payment request pending: ${money(latest.amount_cents)} · requested ${new Date(latest.requested_at).toLocaleString('en-ZA')}`;$('earnRequestPayout').disabled=true}else if(latest?.status==='paid'){out.textContent=`Available to request now: ${money(available)} · last request ${money(latest.amount_cents)} was paid.`;$('earnRequestPayout').disabled=available<2000}else if(latest?.status==='rejected'){out.textContent=`Available to request now: ${money(available)} · last request was not paid${latest.admin_note?' ('+latest.admin_note+')':''}.`;$('earnRequestPayout').disabled=available<2000}else{out.textContent=`Available Earned balance for payment: ${money(available)} · minimum R20.00.`;$('earnRequestPayout').disabled=available<2000}}catch(e){out.textContent='Payment requests unavailable until the payout SQL update is installed: '+e.message;$('earnRequestPayout').disabled=true}}
async function loadPlayerPayoutReviews(){const box=$('earnPayoutReviews');if(!box)return;box.replaceChildren();try{const rows=await rpc('tenotemo_admin_pending_player_payouts');for(const r of rows||[]){const row=document.createElement('article');row.className='earn-campaign';row.append(text('strong',`${r.username} · ${money(r.amount_cents)}`),text('p',`Requested ${new Date(r.requested_at).toLocaleString('en-ZA')}`),text('p',`Account holder: ${r.account_holder}\nBank: ${r.bank_name}\nAccount: ${r.account_number}\nType: ${r.account_type}${r.branch_code?'\nBranch: '+r.branch_code:''}`));const paid=text('button','Mark Paid');paid.type='button';paid.onclick=async()=>{if(!confirm(`Confirm you have made the ${money(r.amount_cents)} EFT to ${r.username} using the bank details shown?`))return;try{await rpc('tenotemo_admin_review_player_payout',{p_request_id:r.request_id,p_paid:true,p_note:'EFT paid by administrator'});note(`${money(r.amount_cents)} marked Paid for ${r.username}.`);await loadPlayerPayoutReviews();await refresh()}catch(e){note(e.message)}};const reject=text('button','Reject request');reject.type='button';reject.onclick=async()=>{const why=prompt('Reason for rejecting this payment request:','Payment details need correction');if(why===null)return;try{await rpc('tenotemo_admin_review_player_payout',{p_request_id:r.request_id,p_paid:false,p_note:why});await loadPlayerPayoutReviews()}catch(e){note(e.message)}};row.append(paid,reject);box.append(row)}if(!(rows||[]).length)box.append(text('p','No player payment requests waiting.'))}catch(e){box.append(text('p','Player payout review unavailable: '+e.message))}}
async function loadAdvertisers(){const list=$('earnAdvertiserList');list.replaceChildren();try{const rows=await rpc('tenotemo_admin_advertiser_search',{p_search:val('earnAdvertiserSearch')});for(const a of rows||[]){const row=text('p',`${a.username} · ${a.display_name} · ${a.account_type} · ${a.preferred_package}`);const b=text('button','Select advertiser');b.onclick=()=>{$('earnCompanyId').value=a.user_id;$('earnPackage').value=a.preferred_package;syncBudget();$('earnSelectedAdvertiser').textContent=`Selected: ${a.username} · EFT reference: ${a.payment_reference}`};row.append(b);list.append(row)}if(!(rows||[]).length)list.append(text('p','No advertiser applications found.'))}catch(e){list.append(text('p','Advertiser directory unavailable: '+e.message))}}
$('earnAdvertiserSearchBtn').onclick=loadAdvertisers;$('earnAdvertiserSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();loadAdvertisers()}});
function showEarnSection(which){for(const id of ['earnPlayerSection','earnBusinessSection','earnAdminSection']){const el=$(id);if(el)el.hidden=id!==which}if($('earnPlayerTab'))$('earnPlayerTab').setAttribute('aria-pressed',which==='earnPlayerSection');if($('earnBusinessTab'))$('earnBusinessTab').setAttribute('aria-pressed',which==='earnBusinessSection');if($('earnAdminTab'))$('earnAdminTab').setAttribute('aria-pressed',which==='earnAdminSection');if(panel){panel.scrollTop=0;requestAnimationFrame(()=>{panel.scrollTop=0})}}
$('earnPlayerTab').onclick=()=>showEarnSection('earnPlayerSection');$('earnBusinessTab').onclick=()=>showEarnSection('earnBusinessSection');$('earnAdminTab').onclick=()=>showEarnSection('earnAdminSection');
$('earnOpen').onclick=async()=>{panel.classList.add('open');panel.scrollTop=0;showEarnSection('earnPlayerSection');refresh();loadPayoutHome();loadMyCreatives();try{const isAdmin=await rpc('tenotemo_is_admin');$('earnAdmin').hidden=!isAdmin;$('earnAdminTab').hidden=!isAdmin;if(isAdmin){loadAdvertisers();loadLaunchSetup();loadManagedCampaigns();loadProofReviews();loadPaymentProofReviews();loadPlayerPayoutReviews();loadCreativeReviews()}}catch{$('earnAdmin').hidden=true;$('earnAdminTab').hidden=true}};
async function loadMyCreatives(){const box=$('earnMyCreatives');if(!box)return;box.replaceChildren();try{const rows=await rpc('tenotemo_my_advertiser_creatives');for(const c of rows||[]){const row=text('article','');row.className='earn-campaign';row.append(text('strong',`${c.title} · ${c.requested_credits} Advertising Credits`),text('p',`${String(c.status).toUpperCase()}${c.target_url?' · Link supplied':''}${c.admin_note?' · '+c.admin_note:''}`));box.append(row)}if(!(rows||[]).length)box.append(text('p','No posters submitted yet.'))}catch(e){box.append(text('p','Poster submissions unavailable until the multi-poster SQL update is installed: '+e.message))}}
let creativePreviewURL=null;
$('earnCreativeMedia').addEventListener('change',()=>{const box=$('earnCreativePreview'),f=$('earnCreativeMedia').files[0];box.replaceChildren();if(creativePreviewURL)URL.revokeObjectURL(creativePreviewURL);if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024){$('earnCreativeMedia').value='';return $('earnCreativeStatus').textContent='Use a JPG, PNG or WebP picture up to 5 MB.'}creativePreviewURL=URL.createObjectURL(f);const im=document.createElement('img');im.src=creativePreviewURL;im.style.cssText='display:block;width:100%;max-height:360px;object-fit:contain;border-radius:12px;margin-top:8px';box.append(im)});
$('earnSubmitCreative').onclick=async()=>{const b=$('earnSubmitCreative'),out=$('earnCreativeStatus'),f=$('earnCreativeMedia').files[0],credits=Number(val('earnCreativeCredits')),url=val('earnCreativeUrl');if(!val('earnCreativeTitle'))return out.textContent='Add a poster title.';if(!f)return out.textContent='Choose a poster/picture.';if(!Number.isInteger(credits)||credits<1)return out.textContent='Advertising Credits must be a whole number of at least 1.';if(url&&!/^https:\/\/[^\s]+$/i.test(url))return out.textContent='Use a complete HTTPS link, or leave the link blank.';let path='';b.disabled=true;try{const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[f.type];if(!ext||f.size>5*1024*1024)throw Error('Use a JPG, PNG or WebP picture up to 5 MB.');path=`${tUser.id}/advertiser-creatives/${crypto.randomUUID()}.${ext}`;const up=await tClient.storage.from('tenotemo-campaign-media').upload(path,f,{contentType:f.type,upsert:false});if(up.error)throw up.error;await rpc('tenotemo_submit_advertiser_creative',{p_title:val('earnCreativeTitle'),p_message:val('earnCreativeMessage'),p_target_url:url||null,p_media_path:path,p_requested_credits:credits});out.textContent='Poster submitted for administrator approval.';$('earnCreativeTitle').value='';$('earnCreativeMessage').value='';$('earnCreativeUrl').value='';$('earnCreativeMedia').value='';$('earnCreativePreview').replaceChildren();await loadMyCreatives();if(!$('earnAdmin').hidden)await loadCreativeReviews()}catch(e){if(path)await tClient.storage.from('tenotemo-campaign-media').remove([path]);out.textContent='Poster not submitted: '+e.message}finally{b.disabled=false}};
$('earnRefreshCreatives').onclick=loadMyCreatives;
function openSignedFile(bucket,path){const w=window.open('about:blank','_blank');if(w)w.opener=null;return tClient.storage.from(bucket).createSignedUrl(path,300).then(x=>{if(x.error){if(w)w.close();throw x.error}if(w)w.location.href=x.data.signedUrl;else window.location.href=x.data.signedUrl;return x.data.signedUrl})}
async function loadCreditSummary(){const box=$('earnCreditSummary');if(!box)return;box.replaceChildren();try{const rows=await rpc('tenotemo_admin_advertising_credit_summary');for(const r of rows||[]){const row=document.createElement('article');row.className='earn-campaign';row.append(text('strong',`${r.username} · ${r.display_name||'Advertiser'} · ${String(r.package_key||'').toUpperCase()}`),text('p',`Purchased: ${r.purchased_credits} · Allocated: ${r.allocated_credits} · Used: ${r.used_credits}`),text('p',`Allocated remaining: ${r.allocated_remaining_credits} · Unallocated available: ${r.unallocated_credits} · Total available: ${r.total_available_credits}`),text('small',`${r.approved_posts} approved qualifying post(s) · ${r.pending_posters} poster submission(s) awaiting review`));box.append(row)}if(!(rows||[]).length)box.append(text('p','No advertiser packages have been granted yet.'))}catch(e){box.append(text('p','Advertising Credit balances unavailable: '+e.message))}}
if($('earnCreditSummaryRefresh'))$('earnCreditSummaryRefresh').onclick=loadCreditSummary;
async function loadCreativeReviews(){const box=$('earnCreativeAdminList');if(!box)return;box.replaceChildren();try{const rows=await rpc('tenotemo_admin_pending_advertiser_creatives');for(const c of rows||[]){const row=text('article','');row.className='earn-campaign';row.append(text('strong',`${c.username} · ${c.display_name||''} · ${c.title}`),text('p',`${c.requested_credits} Advertising Credits requested${c.target_url?' · '+c.target_url:''}`),text('p',c.message||'No message'));const view=text('button','View poster');view.onclick=async()=>{try{await openSignedFile('tenotemo-campaign-media',c.media_path)}catch(e){note('Cannot open poster: '+e.message)}};const yes=text('button','Approve poster');yes.onclick=async()=>{await rpc('tenotemo_admin_review_advertiser_creative',{p_creative_id:c.id,p_approve:true,p_note:'Approved for campaign publishing'});note('Poster approved. Use Publish a campaign to place it on Spotlight and allocate its credits.');await loadCreativeReviews()};const no=text('button','Reject');no.onclick=async()=>{const why=prompt('Reason for rejection:','Poster/content requires changes');if(why===null)return;await rpc('tenotemo_admin_review_advertiser_creative',{p_creative_id:c.id,p_approve:false,p_note:why});await loadCreativeReviews()};row.append(view,yes,no);box.append(row)}if(!(rows||[]).length)box.append(text('p','No poster submissions waiting for review.'))}catch(e){box.append(text('p','Poster review unavailable: '+e.message))}}
$('earnCreativeAdminRefresh').onclick=loadCreativeReviews;
$('earnSaveAdvertiser').onclick=async()=>{const b=$('earnSaveAdvertiser');b.disabled=true;try{await rpc('tenotemo_advertiser_register',{p_type:val('earnAdvertiserType'),p_name:val('earnAdvertiserName'),p_service:val('earnAdvertiserService'),p_area:val('earnAdvertiserArea'),p_package:val('earnAdvertiserPackage')});$('earnAdvertiserStatus').textContent='Application saved. Use the payment details shown here, then upload your proof of payment.';note('Advertiser profile saved. Your Spotlight post and EFT require admin approval.');if(!$('earnAdmin').hidden)loadAdvertisers()}catch(e){$('earnAdvertiserStatus').textContent=e.message}finally{b.disabled=false}};
const val=id=>$(id).value.trim();
const budgets={individual:60,starter:300,growth:900,premium:3000};
function syncBudget(){const n=budgets[val('earnPackage')];$('earnBudget').value=String(n);$('earnBudget').max=String(n);$('earnPackageBudgetInfo').textContent=`Advertising Credits in this package: ${n}. Each credit covers up to 2 approved qualifying posts from the same participant.`}
$('earnPackage').addEventListener('change',syncBudget);syncBudget();

let launchAdvertisers=[];
async function loadLaunchSetup(){
 const sel=$('earnLaunchAdvertiser'),previous=sel.value;
 try{const data=await rpc('tenotemo_admin_campaign_setup');launchAdvertisers=data.advertisers||[];
 sel.replaceChildren(new Option('Select advertiser',''));
 for(const a of launchAdvertisers){const active=a.package_key&&new Date(a.expires_at)>new Date();
 const label=`${a.display_name} · ${active?a.package_key+' active':'PACKAGE REQUIRED'} · ${a.user_id.slice(0,8)}`;
 sel.add(new Option(label,a.user_id))}
 if(launchAdvertisers.some(a=>a.user_id===previous))sel.value=previous;
 updateLaunchSelection();
 }catch(e){$('earnLaunchPackageStatus').textContent='Cannot load advertiser packages: '+e.message}
}
function updateLaunchSelection(){
 const a=launchAdvertisers.find(x=>x.user_id===$('earnLaunchAdvertiser').value);
 if(!a){$('earnLaunchPackageStatus').textContent='Select an advertiser with an active package.';return}
 $('earnCompanyId').value=a.user_id;
 if(a.preferred_package&&[...$('earnPackage').options].some(o=>o.value===a.preferred_package)){$('earnPackage').value=a.preferred_package;syncBudget()}
 const active=a.package_key&&new Date(a.expires_at)>new Date();
 const remaining=Math.max(0,(a.reward_allowance_cents||0)-(a.reserved_cents||0));
 $('earnLaunchPackageStatus').textContent=active?`Active ${a.package_key} package · ${a.granted_spotlight_credits} Advertising Credits granted`:'No active package. Confirm cleared EFT and grant a package first.';
 $('earnLaunchBudget').max=(remaining/100).toFixed(2);
 $('earnLaunchBudget').value=(remaining/100).toFixed(2);
 $('earnLaunchButton').disabled=!active||remaining<=0;
}
const MEDIA_BUCKET='tenotemo-campaign-media';
const MEDIA_TYPES={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','video/mp4':'mp4','video/webm':'webm','video/quicktime':'mov'};
function videoFile(f){return f&&f.type.startsWith('video/')}
async function checkCampaignMedia(file){
 if(!file)return;
 if(!MEDIA_TYPES[file.type])throw Error('Choose a JPG, PNG, WebP, MP4, WebM or MOV file.');
 if(file.size>(videoFile(file)?30:5)*1024*1024)throw Error(videoFile(file)?'Video must be 30 MB or smaller.':'Picture must be 5 MB or smaller.');
 if(videoFile(file)){
  const duration=await new Promise((resolve,reject)=>{
   const el=document.createElement('video'),url=URL.createObjectURL(file);
   const done=(value,err)=>{URL.revokeObjectURL(url);el.removeAttribute('src');el.load();err?reject(err):resolve(value)};
   el.preload='metadata';el.onloadedmetadata=()=>done(el.duration);el.onerror=()=>done(null,Error('Cannot read video. Try MP4 or WebM.'));
   el.src=url;
  });
  if(!Number.isFinite(duration)||duration<=0||duration>30)throw Error('Video must be 30 seconds or shorter.');
 }
}
let mediaPreviewURL=null;
$('earnLaunchMedia').addEventListener('change',async()=>{
 const box=$('earnLaunchMediaPreview'),file=$('earnLaunchMedia').files[0];box.replaceChildren();
 if(mediaPreviewURL){URL.revokeObjectURL(mediaPreviewURL);mediaPreviewURL=null}
 if(!file)return;
 try{await checkCampaignMedia(file);mediaPreviewURL=URL.createObjectURL(file);
 const el=document.createElement(videoFile(file)?'video':'img');el.src=mediaPreviewURL;
 el.style.cssText='display:block;max-width:100%;max-height:240px;border-radius:12px';
 if(videoFile(file)){el.controls=true;el.playsInline=true;el.preload='metadata'}
 box.append(el);
 }catch(e){$('earnLaunchMedia').value='';box.textContent=e.message}
});
$('earnLaunchAdvertiser').addEventListener('change',updateLaunchSelection);
$('earnLaunchEnd').value=(()=>{const d=new Date(Date.now()+14*86400000);return d.toISOString().slice(0,10)})();
$('earnLaunchButton').onclick=async()=>{
 const b=$('earnLaunchButton'),a=launchAdvertisers.find(x=>x.user_id===$('earnLaunchAdvertiser').value);
 if(!a)return $('earnLaunchResult').textContent='Select an advertiser first.';
 const cents=Math.round(Number(val('earnLaunchBudget'))*100),cost=Number(val('earnLaunchCost'));
 if(!Number.isSafeInteger(cents)||cents<0||cents>(a.reward_allowance_cents-a.reserved_cents)||!Number.isInteger(cost)||cost<0||cost>50)return $('earnLaunchResult').textContent='Check the budget and Memory Credit cost.';
 if(!val('earnLaunchEnd'))return $('earnLaunchResult').textContent='Choose an end date.';
 if(!val('earnLaunchUrl')||!/^https:\/\/[^\s]+$/i.test(val('earnLaunchUrl')))return $('earnLaunchResult').textContent='Add a complete HTTPS advertiser link so referral links can open the campaign.';
 if(!confirm('Has the advertiser approved this message and have you confirmed its paid package? Publish this Spotlight post and campaign now?'))return;
 b.disabled=true;$('earnLaunchResult').textContent='Publishing…';
 let uploadedPath=null;
 try{
 const file=$('earnLaunchMedia').files[0];
 if(file){
 await checkCampaignMedia(file);
 uploadedPath=`${tUser.id}/campaigns/${crypto.randomUUID()}.${MEDIA_TYPES[file.type]}`;
 $('earnLaunchResult').textContent='Uploading approved campaign media…';
 const result=await tClient.storage.from(MEDIA_BUCKET).upload(uploadedPath,file,{contentType:file.type,upsert:false});
 if(result.error)throw result.error;
 }
 $('earnLaunchResult').textContent='Publishing approved Spotlight and Earn campaign…';
 const id=await rpc('tenotemo_admin_launch_campaign_media',{
 p_company_id:a.user_id,p_message:val('earnLaunchMessage'),p_title:val('earnLaunchTitle'),
 p_description:val('earnLaunchDescription'),p_target_url:val('earnLaunchUrl'),
 p_budget_cents:cents,p_credit_cost:cost,p_media_path:uploadedPath,p_ends_at:new Date(val('earnLaunchEnd')+'T23:59:59+02:00').toISOString()});
 $('earnLaunchResult').textContent='✅ Published! Campaign '+id+' is now active in Tenotemo Earn and its approved post is on Spotlight.';
 await refresh();await loadLaunchSetup();await loadManagedCampaigns();
 }catch(e){
 if(uploadedPath){const removed=await tClient.storage.from(MEDIA_BUCKET).remove([uploadedPath]);if(removed.error)console.warn('Orphan media cleanup:',removed.error.message)}
 $('earnLaunchResult').textContent='Not published: '+e.message
 }
 finally{b.disabled=false;updateLaunchSelection()}
};

let managedCampaigns=[],editingCampaign=null,editPreviewURL=null;
const manageStatus=s=>$('earnManageNotice').textContent=s;
function editDate(iso){return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(iso))}
async function loadManagedCampaigns(){
 const box=$('earnManagedCampaigns');box.replaceChildren();manageStatus('Loading campaigns…');
 try{managedCampaigns=await rpc('tenotemo_admin_manage_campaigns');
 if(!managedCampaigns.length)box.append(text('p','No linked Earn campaigns yet. Older standalone Spotlight posts are not Earn campaigns.'));
 for(const c of managedCampaigns){const row=text('article','');row.className='earn-campaign';
 row.append(text('h4',`${c.title} · ${c.status.toUpperCase()}`),text('p',`${c.advertiser_name} · ${c.message||'No message'}`),text('small',`${c.enrolments} enrolled · Up to 2 approved qualifying posts per participant · Ends ${new Date(c.ends_at).toLocaleDateString('en-ZA')} · Spotlight ${c.post_status}`));
 if(c.image_path){const p=text('p',c.image_path.match(/\.(mp4|webm|mov)$/i)?'🎬 Video attached':'🖼️ Picture attached');row.append(p)}
 if(c.status!=='closed'){
 const edit=text('button','✏️ Edit');edit.onclick=()=>openManagedEdit(c);row.append(edit);
 const change=text('button',c.status==='active'?'⏸ Pause':'▶ Resume');change.onclick=()=>changeManagedStatus(c,c.status==='active'?'paused':'active');row.append(change);
 const end=text('button','⛔ End campaign');end.onclick=()=>changeManagedStatus(c,'closed');row.append(end);
 }box.append(row)}manageStatus(`Showing ${managedCampaigns.length} linked campaigns.`)
 }catch(e){manageStatus('Unable to load campaigns: '+e.message)}
}
function openManagedEdit(c){editingCampaign=c;$('earnManageEditor').hidden=false;
 $('earnManageEditorHeading').textContent='Edit: '+c.title;
 for(const [id,v] of [['earnEditTitle',c.title],['earnEditMessage',c.message],['earnEditDescription',c.description],['earnEditUrl',c.target_url||''],['earnEditCost',c.credit_cost],['earnEditEnd',editDate(c.ends_at)]])$(id).value=v??'';
 $('earnEditMedia').value='';$('earnEditMediaPreview').replaceChildren();
 $('earnManageEditor').scrollIntoView({behavior:'smooth',block:'start'});
 manageStatus('Editing existing campaign. Leave the media field empty to keep its current picture or video.');
}
$('earnManageRefresh').onclick=loadManagedCampaigns;
$('earnEditCancel').onclick=()=>{editingCampaign=null;$('earnManageEditor').hidden=true};
$('earnEditMedia').onchange=async()=>{const file=$('earnEditMedia').files[0],box=$('earnEditMediaPreview');box.replaceChildren();if(editPreviewURL)URL.revokeObjectURL(editPreviewURL);editPreviewURL=null;if(!file)return;
 try{await checkCampaignMedia(file);editPreviewURL=URL.createObjectURL(file);const el=document.createElement(videoFile(file)?'video':'img');el.src=editPreviewURL;el.style.cssText='display:block;max-width:100%;max-height:220px';if(videoFile(file)){el.controls=true;el.playsInline=true}box.append(el)}catch(e){$('earnEditMedia').value='';manageStatus(e.message)}};
$('earnEditSave').onclick=async()=>{const c=editingCampaign;if(!c)return;
 const b=$('earnEditSave'),file=$('earnEditMedia').files[0],url=val('earnEditUrl'),cost=Number(val('earnEditCost'));
 if(!/^https:\/\/[^\s]+$/i.test(url))return manageStatus('A complete HTTPS advertiser link is required.');
 if(!Number.isInteger(cost)||cost<0||cost>50)return manageStatus('Memory Credit cost must be 0–50.');
 if(!val('earnEditEnd'))return manageStatus('Choose an end date.');
 if(!confirm('Save these changes to the existing Spotlight post and Earn campaign?'))return;
 let uploadedPath=null;b.disabled=true;
 try{if(file){await checkCampaignMedia(file);uploadedPath=`${tUser.id}/campaigns/${crypto.randomUUID()}.${MEDIA_TYPES[file.type]}`;manageStatus('Uploading replacement media…');const u=await tClient.storage.from(MEDIA_BUCKET).upload(uploadedPath,file,{contentType:file.type,upsert:false});if(u.error)throw u.error}
 manageStatus('Saving linked campaign and Spotlight post…');await rpc('tenotemo_admin_edit_campaign',{p_campaign_id:c.id,p_title:val('earnEditTitle'),p_message:val('earnEditMessage'),p_description:val('earnEditDescription'),p_target_url:url,p_media_path:uploadedPath,p_credit_cost:cost,p_ends_at:new Date(val('earnEditEnd')+'T23:59:59+02:00').toISOString()});
 editingCampaign=null;$('earnManageEditor').hidden=true;await loadManagedCampaigns();await refresh();manageStatus('✅ Campaign updated. Existing referral records and approved rewards are retained.');
 }catch(e){if(uploadedPath){const r=await tClient.storage.from(MEDIA_BUCKET).remove([uploadedPath]);if(r.error)console.warn('Media cleanup:',r.error.message)}manageStatus('Not saved: '+e.message)}finally{b.disabled=false}};
async function changeManagedStatus(c,status){const wording=status==='closed'?'Permanently end this campaign? It cannot be resumed. Player referral and reward records remain.':status==='paused'?'Pause this campaign and hide its Spotlight post?':'Resume this campaign and show its Spotlight post?';if(!confirm(wording))return;
 try{await rpc('tenotemo_admin_campaign_status',{p_campaign_id:c.id,p_status:status});if(editingCampaign?.id===c.id){editingCampaign=null;$('earnManageEditor').hidden=true}await loadManagedCampaigns();await refresh();manageStatus(`Campaign ${status}. Spotlight visibility updated.`)}catch(e){manageStatus('Status not changed: '+e.message)}}

$('earnGrantPackage').onclick=async()=>{if(!confirm('Have you verified cleared EFT funds? This will grant company exposure immediately.'))return;try{await rpc('tenotemo_admin_company_package',{p_company_id:val('earnCompanyId'),p_package:val('earnPackage')});note('Advertiser package granted. You can now publish a campaign below.');loadAdvertisers();await loadLaunchSetup();await loadCreditSummary()}catch(e){note(e.message)}};
$('earnCreateCampaign').onclick=async()=>{try{const cents=Math.round(Number(val('earnBudget'))*100);const cost=Number(val('earnCost'));if(!Number.isSafeInteger(cents)||cents<0||cents>budgets[val('earnPackage')]*100||!Number.isInteger(cost))throw Error('Invalid budget or credit cost');const end=new Date(val('earnEnd')+'T23:59:59+02:00').toISOString();const id=await rpc('tenotemo_admin_campaign',{p_company_id:val('earnCompanyId'),p_post_id:val('earnPostId'),p_title:val('earnTitle'),p_description:val('earnDescription'),p_budget_cents:cents,p_credit_cost:cost,p_ends_at:end});note('Campaign created: '+id);await refresh()}catch(e){note(e.message)}};
async function searchPlayerEnrolments(){const box=$('earnPlayerResults');box.replaceChildren();try{const rows=await rpc('tenotemo_admin_player_enrolments',{p_search:val('earnPlayerSearch')});for(const r of rows||[]){const row=text('p',`${r.username} · ${r.campaign_title} · Earned ${money(r.approved_cents)} · Paid ${money(r.paid_cents)}`);const b=text('button','Select');b.type='button';b.onclick=()=>{$('earnEnrolment').value=r.enrolment_id;$('earnSelectedPlayer').textContent=`Selected: ${r.username} · ${r.campaign_title} · EFT reference: ${r.payment_reference}`};row.append(b);box.append(row)}if(!(rows||[]).length)box.append(text('p','No enrolled players found.'))}catch(e){box.append(text('p','Player search unavailable: '+e.message))}}
$('earnPlayerSearchBtn').onclick=searchPlayerEnrolments;$('earnPlayerSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchPlayerEnrolments()}});
async function loadProofReviews(){const box=$('earnProofReviews');box.replaceChildren();try{const rows=await rpc('tenotemo_admin_pending_share_proofs');for(const r of rows||[]){const row=document.createElement('article');row.className='earn-campaign';const isCash=r.reward_type==='cash';const sharedAt=r.shared_at?new Date(r.shared_at):null;const ageHours=sharedAt?(Date.now()-sharedAt.getTime())/3600000:0;const eligible=ageHours>2&&Number(r.view_count)>=21;row.append(text('strong',`${r.username} · ${r.campaign_title}`),text('p',`${r.platform} · ${isCash?'R1 cash reward':'5 Memory Credits'} · ${Number(r.view_count||0)} views`),text('p',sharedAt?`Shared ${sharedAt.toLocaleString('en-ZA')} · Live for ${Math.max(0,ageHours).toFixed(1)} hours`:'Share time missing'),text('p',eligible?'✓ Meets recorded 2-hour / 21-view thresholds — verify screenshot before approval.':'⚠ Not yet eligible for approval: requires more than 2 hours live and at least 21 views.'),...(isCash?[text('p',`EFT reference when paid: ${r.payment_reference}`)]:[]));const view=text('button','View screenshot');view.type='button';view.onclick=async()=>{try{await openSignedFile('tenotemo-share-proofs',r.proof_path)}catch(e){note('Cannot open proof: '+e.message)}};const yes=text('button',isCash?'Approve R1':'Approve 5 Memory Credits');yes.type='button';yes.disabled=!eligible;yes.onclick=async()=>{if(!confirm(`Approve ${isCash?'R1':'5 Memory Credits'} for ${r.username}? Confirm the screenshot supports the platform, 21+ views and qualifying share.`))return;try{await rpc('tenotemo_admin_review_share_proof',{p_proof_id:r.proof_id,p_approve:true,p_note:'Screenshot verified by admin: platform, 21+ views and 2+ hours confirmed'});note(`${isCash?'R1 earned':'5 Memory Credits awarded'} by ${r.username}.`);await loadProofReviews();await refresh()}catch(e){note(e.message)}};const no=text('button','Reject');no.type='button';no.onclick=async()=>{const why=prompt('Reason for rejection:','Proof does not show a qualifying published campaign share with 21+ views');if(why===null)return;try{await rpc('tenotemo_admin_review_share_proof',{p_proof_id:r.proof_id,p_approve:false,p_note:why});await loadProofReviews()}catch(e){note(e.message)}};row.append(view,yes,no);box.append(row)}if(!(rows||[]).length)box.append(text('p','No share proofs waiting for review.'))}catch(e){box.append(text('p','Proof review unavailable: '+e.message))}}
$('earnProofRefresh').onclick=loadProofReviews;
$('earnApproveReward').onclick=async()=>{if(!confirm('Confirm referral/customer evidence was independently reviewed and the company reward budget is funded?'))return;try{const cents=Math.round(Number(val('earnRewardAmount'))*100);if(!Number.isSafeInteger(cents)||cents<=0)throw Error('Invalid amount');await rpc('tenotemo_admin_reward',{p_enrolment_id:val('earnEnrolment'),p_amount_cents:cents,p_reason:val('earnReason')});note('Reward approved and added to earned balance. Use the selected player username as the EFT payment reference.');await refresh()}catch(e){note(e.message)}};
$('earnClaimPoints').onclick=async()=>{const b=$('earnClaimPoints');b.disabled=true;try{const rows=await rpc('tenotemo_claim_game_point_credits');const r=Array.isArray(rows)?rows[0]:rows;note(`Converted ${Number(r.credits_added||0)} Memory Credits from game points. ${Number(r.remaining_points||0)} points remain toward your next credit.`);await refresh()}catch(e){note(e.message)}finally{b.disabled=false}};
$('earnSavePayoutDetails').onclick=async()=>{const b=$('earnSavePayoutDetails');b.disabled=true;try{const acct=val('earnPayoutAccount');if(!acct)throw Error('Enter the account number when saving or changing EFT details.');await rpc('tenotemo_save_player_payout_details',{p_account_holder:val('earnPayoutHolder'),p_bank_name:val('earnPayoutBank'),p_account_number:acct,p_account_type:val('earnPayoutType'),p_branch_code:val('earnPayoutBranch')||null});$('earnPayoutAccount').value='';note('Your private EFT payment details were saved.');await loadPayoutHome()}catch(e){note('Payment details not saved: '+e.message)}finally{b.disabled=false}};
$('earnRequestPayout').onclick=async()=>{const b=$('earnRequestPayout');if(!confirm('Request payment of all currently eligible Earned earnings? Minimum R20.00.'))return;b.disabled=true;try{const rows=await rpc('tenotemo_request_player_payout');const r=Array.isArray(rows)?rows[0]:rows;note(`Payment request submitted for ${money(r.amount_cents)}. Your bank details are visible only to authorised payout administration.`);await loadPayoutHome();await refresh()}catch(e){note(e.message);await loadPayoutHome()}finally{if(!$('earnPayoutStatus').textContent.includes('pending'))b.disabled=false}};
$('earnPayoutRefresh').onclick=loadPlayerPayoutReviews;
$('earnSubmitPaymentProof').onclick=async()=>{const b=$('earnSubmitPaymentProof'),f=$('earnPaymentProof').files[0],out=$('earnPaymentProofStatus');if(!f)return out.textContent='Choose a screenshot, photo or PDF first.';if(f.size>8*1024*1024)return out.textContent='Proof must be 8 MB or smaller.';if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(f.type))return out.textContent='Use JPG, PNG, WebP or PDF.';let path='';b.disabled=true;try{const ext=f.type==='application/pdf'?'pdf':(f.name.split('.').pop()||'jpg').toLowerCase();path=`${tUser.id}/advertiser-payments/${crypto.randomUUID()}.${ext}`;const up=await tClient.storage.from('tenotemo-payment-proofs').upload(path,f,{contentType:f.type,upsert:false});if(up.error)throw up.error;await rpc('tenotemo_submit_advertiser_payment_proof',{p_proof_path:path});out.textContent='Proof submitted. An administrator will review it before your package is activated.';note('Payment proof submitted for review.');$('earnPaymentProof').value=''}catch(e){if(path)await tClient.storage.from('tenotemo-payment-proofs').remove([path]);out.textContent='Proof not submitted: '+e.message}finally{b.disabled=false}};
async function loadPaymentProofReviews(){const box=$('earnPaymentProofReviews');if(!box)return;box.replaceChildren();try{const rows=await rpc('tenotemo_admin_pending_payment_proofs');for(const r of rows||[]){const row=document.createElement('article');row.className='earn-campaign';row.append(text('strong',`${r.username} · ${r.display_name}`),text('p',`Requested package: ${r.preferred_package} · Submitted ${new Date(r.submitted_at).toLocaleString('en-ZA')}`),text('p',`EFT reference: ${r.payment_reference}`));const view=text('button','View proof');view.onclick=async()=>{try{await openSignedFile('tenotemo-payment-proofs',r.proof_path)}catch(e){note('Cannot open payment proof: '+e.message)}};const yes=text('button','Approve proof');yes.onclick=async()=>{if(!confirm(`Mark payment proof for ${r.username} as verified? Confirm funds in the bank separately before granting the package.`))return;await rpc('tenotemo_admin_review_payment_proof',{p_proof_id:r.proof_id,p_approve:true,p_note:'Payment proof reviewed by admin'});await loadPaymentProofReviews();note('Payment proof approved. You can now select the advertiser and grant the paid package.')};const no=text('button','Reject proof');no.onclick=async()=>{const why=prompt('Reason for rejection:','Payment proof could not be verified');if(why===null)return;await rpc('tenotemo_admin_review_payment_proof',{p_proof_id:r.proof_id,p_approve:false,p_note:why});await loadPaymentProofReviews()};row.append(view,yes,no);box.append(row)}if(!(rows||[]).length)box.append(text('p','No advertiser payment proofs waiting for review.'))}catch(e){box.append(text('p','Payment proof review unavailable: '+e.message))}}
$('earnPaymentProofRefresh').onclick=loadPaymentProofReviews;
$('earnClose').onclick=()=>panel.classList.remove('open');
$('earnClaim').onclick=async()=>{const b=$('earnClaim');b.disabled=true;try{const rows=await rpc('tenotemo_claim_daily_challenges_today');const r=rows[0];note(`Claimed ${r.completion_credits} today's Daily Challenge Memory Credits.`);await refresh()}catch(e){note(e.message)}finally{b.disabled=false}};
$('earnClaimTop50').onclick=async()=>{const b=$('earnClaimTop50');b.disabled=true;try{const d=$('earnClaimDate').value;const rows=await rpc('tenotemo_claim_top50_day',{p_date:d});const r=rows[0];note(`Claimed ${r.top50_credits} Top 50 Memory Credits for ${d}.`);await refresh()}catch(e){note(e.message)}finally{b.disabled=false}};
$('earnClaimDate').value=day(-1);$('earnClaimDate').max=day(-1);
// Spotlight Share & Earn button only appears when its post is tied to an active campaign.
window.tenotemoEarnShareSpotlight=async postId=>{if(!tUser)return note('Sign in first.');panel.classList.add('open');await refresh();const d=await rpc('tenotemo_earn_home');const c=(d.campaigns||[]).find(x=>x.spotlight_post_id===postId);if(c)note('Find the advertiser campaign below to unlock and share it.')};
})();
