/* Tenotemo Online Versus beta: independent identical seeded challenges, server queue and scoreboards.
   Multiplayer league scores are separate from normal-game Daily Top 50 Memory Credits.
   Browser-reported scores are NOT anti-cheat verified: do not attach monetary prizes to Versus. */
(()=>{'use strict';
const $=id=>document.getElementById(id), overlay=$('vsOverlay'),status=$('vsStatus'),prompt=$('vsPrompt'),choices=$('vsChoices'),score=$('vsScore'),next=$('vsNext');
let match=null,poll=null,timer=null,round=0,roundPoints=0,roundAnswers=0,question=0,answer='',deadline=0,phase='idle',seen=false;
const icons=['🐬','🐙','🦀','🐠','🐢','🦈','🐳','🪼','🐚','⭐','💎','🔑','🍋','🍉','🌈','🚀'];
const colours=['🔴','🔵','🟢','🟡','🟣','🟠','🟤','⚫','⚪'];
const gameNames={shape:'Shape Memory',colour:'Colour Grid',pattern:'Pattern Memory',climb:'Constant Climb',spin:'Ocean Spin'};
function rng(seed){let x=(seed>>>0)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296}}
function shuffle(a,r){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function html(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setStatus(s){status.textContent=s}
function clean(){clearInterval(poll);clearInterval(timer);poll=null;timer=null;next.hidden=true;choices.replaceChildren();prompt.textContent=''}
async function rpc(name,args){const {data,error}=await tClient.rpc(name,args||{});if(error)throw error;return data}
function myId(){return tUser?.id}
function opponent(){return match?.player_a===myId()?match?.name_b:match?.name_a}
function otherId(){return match?.player_a===myId()?match?.player_b:match?.player_a}
function rows(){return match?.scores||[]}
function total(id){return rows().filter(x=>x.player_id===id).reduce((s,x)=>s+x.points,0)}
function wins(id){let w=0;for(let i=1;i<=5;i++){let a=rows().find(x=>x.player_id===id&&x.game_number===i),b=rows().find(x=>x.player_id!==(id)&&x.game_number===i);if(a&&b&&a.points>b.points)w++}return w}
function scoreboard(){if(!match){score.textContent='Finding an opponent…';return}score.innerHTML='<span>'+html(playerName)+'<br>'+total(myId())+' pts · '+wins(myId())+' games</span><span>VS<br>Game '+Math.min(round+1,5)+'/5</span><span>'+html(opponent()||'Searching…')+'<br>'+total(otherId())+' pts · '+wins(otherId())+' games</span>'}
async function state(){if(!match)return;try{match=await rpc('tenotemo_versus_state',{p_match_id:match.id});scoreboard();if(match.status==='waiting'){setStatus('Searching for another Premium player… Keep this screen open.');return}if(match.status==='cancelled'){setStatus('Match cancelled. Return to menu and try again.');clearInterval(poll);return}if(match.status==='playing'&&phase==='waiting'){phase='ready';round=rows().filter(x=>x.player_id===myId()).length;beginRound()}if(match.status==='finished'&&phase==='finished')endMatch()}catch(e){setStatus('Connection issue: '+e.message+'. Retrying…')}}
async function join(){if(!tUser){alert('Sign in first.');return}if(!hasSubscription){$('tEftPanel').classList.add('open');if(typeof tEftLoad==='function')tEftLoad();return}clean();overlay.classList.add('open');phase='waiting';round=0;match=null;setStatus('Joining the multiplayer queue…');scoreboard();try{const r=await rpc('tenotemo_versus_join');match={id:r.match_id,status:r.status,scores:[]};await state();poll=setInterval(state,2200)}catch(e){setStatus('Could not join: '+e.message+'. Run tenotemo_multiplayer_migration.sql and check Premium activation.')}}
function getPuzzle(g,i){const seed=(Number(match.seed)+round*19207+i*1009)>>>0,r=rng(seed);let pool=g==='colour'?colours:icons;if(g==='climb'){let a=6+Math.floor(r()*23),b=4+Math.floor(r()*19),op=['+','−','×'][Math.floor(r()*3)];let correct=op==='+'?a+b:op==='−'?a-b:a*b;return {display:a+' '+op+' '+b+' = ?',answer:String(correct),options:shuffle([correct,correct+1,correct-2,correct+3,correct-4,correct+5].map(String),r)}}
if(g==='pattern'){let a=1+Math.floor(r()*7),d=2+Math.floor(r()*6),ans=a+4*d;return {display:[a,a+d,a+2*d,a+3*d,'?'].join(' · '),answer:String(ans),options:shuffle([ans,ans+d,ans-d,ans+1,ans-1,ans+2].map(String),r)}}
if(g==='spin'){let items=shuffle(pool,r).slice(0,5),target=items[Math.floor(r()*5)];return {display:'Remember: '+items.join(' ')+'\nFind: '+target,answer:target,options:shuffle([...items,...shuffle(pool,r).filter(x=>!items.includes(x)).slice(0,1)],r)}}
let items=shuffle(pool,r).slice(0,6),target=items[Math.floor(r()*6)];if(g==='shape'){let pair=items[Math.floor(r()*6)]+' '+items[Math.floor(r()*6)];return {display:'Remember: '+items.join(' ')+'\nSelect: '+target,answer:target,options:shuffle(items,r)}}
return {display:'Memorise: '+items.join(' ')+'\nFind: '+target,answer:target,options:shuffle(items,r)}}
function beginRound(){if(round>=5){phase='finished';setStatus('Your five games are complete. Waiting for opponent to finish…');if(match.status==='finished')endMatch();return}phase='playing';roundPoints=0;roundAnswers=0;question=0;next.hidden=true;scoreboard();setStatus('Hard challenge · '+gameNames[match.order[round]]+' · Same puzzle for both players');newQuestion()}
function newQuestion(){clearInterval(timer);if(question>=5){finishRound();return}let g=match.order[round],p=getPuzzle(g,question);answer=p.answer;choices.replaceChildren();prompt.textContent=p.display;prompt.style.whiteSpace='pre-line';setStatus(gameNames[g]+' · Puzzle '+(question+1)+'/5 · '+roundPoints+' points');p.options.forEach(v=>{let b=document.createElement('button');b.type='button';b.textContent=v;b.onclick=()=>pick(v);choices.append(b)});deadline=Date.now()+11000;timer=setInterval(()=>{let left=Math.max(0,Math.ceil((deadline-Date.now())/1000));setStatus(gameNames[g]+' · Puzzle '+(question+1)+'/5 · '+roundPoints+' points · '+left+'s');if(left===0)pick(null)},200)}
function pick(value){if(phase!=='playing'||seen)return;seen=true;clearInterval(timer);const correct=value===answer;if(correct){roundPoints+=20;roundAnswers++}else if(value!==null){roundPoints=Math.max(0,roundPoints-5)}setStatus(correct?'Correct! +20':value===null?'Time expired':'Incorrect · −5');[...choices.children].forEach(b=>b.disabled=true);setTimeout(()=>{seen=false;question++;if(phase==='playing')newQuestion()},700)}
async function finishRound(){phase='submitting';choices.replaceChildren();prompt.textContent='Game '+(round+1)+' complete: '+roundPoints+' points';setStatus('Saving game score…');try{match=await rpc('tenotemo_versus_submit',{p_match_id:match.id,p_game_number:round+1,p_points:roundPoints});round++;scoreboard();phase='between';setStatus('Score saved. '+(round<5?'Continue to next game.':'Waiting for the other player.'));next.hidden=round>=5;if(round>=5){phase='finished';if(match.status==='finished')endMatch()}}catch(e){phase='retry';setStatus('Score not saved: '+e.message+' · Press Retry');next.hidden=false;next.textContent='Retry save'}}
function endMatch(){clean();phase='complete';let a=wins(myId()),b=wins(otherId());prompt.textContent=a>b?'🏆 You won!':a<b?'Match finished':'🤝 Match drawn';setStatus('Games won '+a+'–'+b+' · Your total '+total(myId())+' · Opponent '+total(otherId())+' · League points '+(a>b?3:a===b?1:0));scoreboard()}
next.onclick=()=>{next.hidden=true;next.textContent='Continue';if(phase==='retry')finishRound();else if(phase==='between'){phase='ready';beginRound()}};
$('vsExit').onclick=async()=>{if(match?.status==='waiting')try{await rpc('tenotemo_versus_cancel',{p_match_id:match.id})}catch(e){console.warn(e)}clean();overlay.classList.remove('open');phase='idle';match=null};
$('versusEntryButton').onclick=join;
$('versusPremiumButton').onclick=()=>{$('tEftPanel').classList.add('open');if(typeof tEftLoad==='function')tEftLoad()};
$('versusLeaderboardButton').onclick=async()=>{const box=$('leaderboardTableContainer');box.textContent='Loading multiplayer standings…';try{const data=await rpc('tenotemo_versus_leaderboard',{p_limit:50});box.innerHTML='<h3>⚔️ Premium Multiplayer · Top 50</h3><p>3 points per match win · 1 per draw · Average game score breaks ties. No cash-prize points.</p><div style="overflow:auto"><table class="leaderboard-table"><thead><tr><th>#</th><th>Player</th><th>P</th><th>W</th><th>D</th><th>L</th><th>League pts</th><th>Avg/game</th></tr></thead><tbody>'+data.map(r=>'<tr><td>'+r.position+'</td><td>'+html(r.player_name)+'</td><td>'+r.played+'</td><td>'+r.wins+'</td><td>'+r.draws+'</td><td>'+r.losses+'</td><td>'+r.league_points+'</td><td>'+r.average_game_points+'</td></tr>').join('')+'</tbody></table></div>'}catch(e){box.textContent='Could not load Versus leaderboard: '+e.message}};
})();
